version: "3.7"

services:
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  scrolls:
    image: ghcr.io/txpipe/scrolls:latest
    command: [ "daemon" ]
    environment:
      - RUST_LOG=info
    volumes:
      - ./daemon.toml:/etc/scrolls/daemon.toml
      
  scrolls-graphql:
    image: scrolls-graphql
    environment:
      - REDIS_URL=redis:6379
    ports:
      - 4000:4000
